### ISSUE TITLE
Option to change instance

### ISSUE THREAD

**Issue by Xenxia** [author-more/penpot-desktop#23] opened 2024-11-23 20:31 UTC
Hello,

I don't know if the functionality to change penpot instances is available, is it in preparation?

**Comment by Belar** [comment] 2024-11-24 16:58
Hi @Xenxia,
you should be able to open any Penpot instance and the feature is not limited by an operating system (from the title changes I assume you are running Penpot Desktop on Windows).

To change the instance, open settings (the cog wheel icon in the top right corner, next to the window controls), change the "Instance" address to the instance you would like to use, click “Save”, and restart the app.

If it's not possible, let me know please.

**Comment by Xenxia** [comment] 2024-11-24 17:59
Hello @Belar,

Thank you for your reply. I don't have a cog weel on the right. I'm on Windows, I don't know if it's a bug?

![image](https://github.com/user-attachments/assets/20142948-245a-4778-a77f-7bd1c5dba615)

**Comment by Belar** [comment] 2024-11-24 20:10
Thank you. It’s a bug. I will release a fix tomorrow.

The issue is with the UI’s positioning only, so the menu is still accessible with keyboard navigation - `Tab` until Settings button (a tooltip will show up from under the controls) and `Enter` to open the settings.

**Comment by Belar** [comment] 2024-11-25 09:10
Fixed in the version [0.4.2](https://github.com/author-more/penpot-desktop/releases/tag/v0.4.2).

**Closed by Belar** 2024-11-25 09:10 UTC
Labels: bug, Windows
